### ISSUE TITLE
Potential Bug in K.squeeze for Theano?

### ISSUE THREAD

**Issue by jmhessel** [fchollet/keras#3431]
[Here](https://gist.github.com/jmhessel/ede93c03ed04824c72ad773e13b37265) is an example of a case where Theano and Tensorflow differ in their behavior with respect to the K.squeeze function. Essentially, [K.squeeze(x, 2)](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L504-L511) doesn't perform as it should in the example I provided, but only when using the Theano backend.

Has anyone else encountered this? Is this indeed a bug? If so, do folks have thoughts about what could be potentially not working?
#3420 also mentions an issue with this function in the Theano backend, though I'm not sure if this is exactly the same issue

**Comment by jmhessel** [comment]
Versions:

```
>>> import keras
Using Theano backend.
>>> keras.__version__
'1.0.7'
```

```
>>> import theano
>>> theano.__version__
'0.9.0dev2.dev-bcd856b497356233a15e0c6e5d8feb193cf53635'
```

**Comment by farizrahman4u** [comment]
I think its got something to do with theano's broadcasting business.

**Comment by dead** [comment]
You need set the output_shape. [Keras lambda layers can't infere](https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L425-L440) the shape from the theano tensor.
I think Keras should warn the user when the number of dimensions of the tensor differs from the "default" output_shape (input_shape).

**Comment by farizrahman4u** [comment]
I have fixed this bug.

**Comment by jmhessel** [comment]
@farizrahman4u Thanks for looking at this! However, even with your bugfix pulled, it looks like the difference in behavior between Theano and TF still persists on the example I gave. Maybe it's not something to be solved, but rather something where a warning should be printed as @dead mentioned?

**Comment by jmhessel** [comment]
@dead 's observation about setting output_shape in the lambda layer fixed this -- should there be a warning printed or something like that? or maybe a requirement that output_shape be set for lambda layers with theano's backend?

**Comment by farizrahman4u** [comment]
The output_shape argument is documented. I have a local patch that infers output shape of Lambda  layer automatically. #2336

**Comment by jmhessel** [comment]
The output_shape argument is documented, but there should potentially be a note (or potentially even a warning that prints if you use Lambda with the theano backend) that states one should _really_ be using the argument with the theano backend.

Basically -- I'm saying that the notes about the differences in behavior between theano and tf that are present in the python comments in the source code should potentially be in the documentation for Lambda as well.

**Comment by jmhessel** [comment]
Warning added ! Closing.

**Comment by jmhessel** [comment]
(for future reference #5132 I think fixes this, though a longer-term solution other than raising an error would probably be better)
