### ISSUE TITLE
Automated tests failing and slow

### ISSUE THREAD

**Issue by tleeuwenburg** [fchollet/keras#397]
Hi all,

I just ran the unit tests. There are a significant number of failures at the moment. 

(/Users/tjl/Development/envs/keras)CSSVIC015225L:keras tjl$ py.test 
============================================================================= test session starts =============================================================================
platform darwin -- Python 3.4.3 -- py-1.4.27 -- pytest-2.7.1
rootdir: /Users/tjl/Development/source_packages/keras, inifile: 
plugins: cov
collected 29 items 

tests/auto/test_embeddings.py .
tests/auto/test_graph_model.py FFFF.
tests/auto/test_loss_weighting.py .
tests/auto/test_regularizers.py ..
tests/auto/test_sequential_model.py FFFFF
tests/auto/test_tasks.py ...FF.
tests/auto/keras/test_activations.py ....
tests/auto/keras/test_constraints.py .....

One of the failures is the result of h5py not being included the setup.py for keras. Others appear to be 'real' failures (bad training scores). 

Do others experience the same failures? I'm seeing similar failures on my travis-ci setup which is running Ubuntu (I'm on OSX). There are some extra passing tests there which Thomas and I have been working on.

If others have the tests passing, then it's likely to be an environmental issue.

If so, that might be an indication there is an issue with code being committed. This could be a good motivation to look at setting up travis on the main repository to confirm changes are moving in the right direction.

**Comment by tleeuwenburg** [comment]
I also note that some of these tests take quite a long time to run. I will try to suggest some strategies for reducing the run-time of these tests so that it's easier for developers to use them when checking the validity of their commits. If the tests do need to run for longer, it's also possible to mark tests as 'slow', and skip them on developer machines and let a nightly build (or travis) pick them up for addressing later.

**Comment by fchollet** [comment]
It seems the issue was with the tests themselves. I fixed it.

Total time taken on my machine is 170s. It's long, though it's still manageable. I agree we'd need to cut that down, but given that by nature our tests consist in *lots* of successive compilations of Theano expressions, it might be difficult to compress it significantly. Compilation takes time.

**Comment by tleeuwenburg** [comment]
Thanks for fixing it up. Tests only help when they go from passing to failing, as a hint to the author of a failing commit. Thanks for your help.

**Comment by tleeuwenburg** [comment]
Still failing on my machine. Need to add h5py to setup.py so it installs with keras as a dependency. Doesn't seem worth doing a merge request -- are you happy to add this? The tests pass after I manually install h5py.
