### ISSUE TITLE
The type of the replacement must be compatible with the type of the original Variable ？ MergeOptimizer

### ISSUE THREAD

**Issue by wdl000001** [fchollet/keras#4001]
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuReshape{4}.0, GpuReshape{4}.0, CudaNdarrayType(float32, (False, False, True, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x00000000345A17B8>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "C:\Anaconda2\lib\site-packages\theano\gof\opt.py", line 817, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "C:\Anaconda2\lib\site-packages\theano\gof\toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\Anaconda2\lib\site-packages\theano\gof\fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuReshape{4}.0, GpuReshape{4}.0, CudaNdarrayType(float32, (False, False, True, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')

**Comment by wdl000001** [comment]
Help me. 
What caused this problem？

**Comment by nouiz** [comment]
First, you can ignore this message. It cause just an optimization to be
skiped. All will still run correctly.

But this is a very strange error. Which version of Theano do you use? Can
you update to theano dev version?

**Comment by RIMcKinley** [comment]
I got a similar error.  Using the latest dev version of theano, python 2.7, Windows 10.

`<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuReshape{4}.0, GpuReshape{4}.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x00000001C2D44390>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "d:\git\theano\theano\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "d:\git\theano\theano\theano\gof\opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "d:\git\theano\theano\theano\gof\opt.py", line 2477, in apply
    sub_prof = gopt.apply(fgraph)
  File "d:\git\theano\theano\theano\gof\opt.py", line 855, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "d:\git\theano\theano\theano\gof\toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "d:\git\theano\theano\theano\gof\fg.py", line 480, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuReshape{4}.0, GpuReshape{4}.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')`

I'm trying to construct a minimal reproduction of the error.

**Comment by nouiz** [comment]
Make sure to use Theano dev version and a recent one. There was fix for
such type of error.

**Comment by RIMcKinley** [comment]
Thanks for the response.  Like I said above, I was using the latest dev build.  I'm away from my machine right now, but it was 0.9 something

**Comment by nouiz** [comment]
Can you give us code that reproduce this? If this is hard, you could also
give us a function_dump:

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

**Comment by RIMcKinley** [comment]
The following reproduces the error.

`import os
os.environ['KERAS_BACKEND'] = 'theano'
os.environ['THEANO_FLAGS']='optimizer=fast_compile,exception_verbosity=high,device=gpu0,floatX=float32'
import theano

print(theano.__version__)
import keras,numpy

from keras.layers import Input
from keras.layers.core import Activation, Reshape
from keras.layers.convolutional import Convolution2D

from keras.models import Model
data_shape = 100
filter_size =12
input_layer1 = Input(shape = (1, 10, 10))

one_by_one_conv_edema = Convolution2D(1, 1, 1, border_mode='valid',)(input_layer1)
reshape_layer_edema = Reshape((data_shape,1))(one_by_one_conv_edema)

themodel = Model(input=input_layer1, 
                    output=reshape_layer_edema)

optimizer = keras.optimizers.SGD(lr=0.01, momentum=0.9, nesterov=True)

themodel.compile(loss="binary_crossentropy", optimizer=optimizer,metrics=[],sample_weight_mode='temporal')

data = numpy.zeros((20,1,10,10))


output = numpy.zeros((20,100,1))

themodel.fit(data,output,verbose=1)`

Theano version is 0.9.0dev4.dev-9cb9ff4db5bf4720c47613348c8a143c3aeaa772

**Comment by RIMcKinley** [comment]
I was able to avoid the error in my actual code by removing the reshape layers reshaping the target data instead, so it must be something to do with the reshape layer.

**Comment by nouiz** [comment]
Just a note, now this should not happen again in Theano. The root should be fixed.

So mostly, if you find this issue and have this problem, update Theano to the dev version of 0.9rc to be released this week.

**Comment by nouiz** [comment]
So mostly, this issue can be closed.

**Comment by mingwugmail** [comment]
I still have this problem, tensorflow runs fine.

Theano (0.9.0)
Keras (2.0.3)


<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Prod{axis=(0,), dtype='flo\
at32', acc_dtype='float64'}.0, Elemwise{mul,no_inplace}.0, TensorType(float32, matrix), TensorType(float64, matrix), 'local_sum_prod_mul_by_scalar') local_sum_prod_mul_by_scalar
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_mul_by_scalar
[2017-04-17 10:57:14,470 opt.py:1858 -                 warn()] Optimization failure due to: local_sum_prod_mul_by_scalar
ERROR (theano.gof.opt): node: Prod{axis=(0,), dtype='float32', acc_dtype='float64'}(Elemwise{mul,no_inplace}.0)
[2017-04-17 10:57:14,471 opt.py:1859 -                 warn()] node: Prod{axis=(0,), dtype='float32', acc_dtype='float64'}(Elemwise{mul,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
[2017-04-17 10:57:14,471 opt.py:1860 -                 warn()] TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Prod{axis=(0,), dtype='float32', acc_dtype='float64'}.0, Elemwise{mul,no_inplace}.0, Tensor\
Type(float32, matrix), TensorType(float64, matrix), 'local_sum_prod_mul_by_scalar')

[2017-04-17 10:57:14,471 opt.py:1861 -                 warn()] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Prod{axis=(0,), dtype='float32', acc_dtype='float64'}.0, Elemwise{mul,no_inplace}.0, Tensor\
Type(float32, matrix), TensorType(float64, matrix), 'local_sum_prod_mul_by_scalar')
