### ISSUE TITLE
v1.1.2 broke `model_from_json()`

### ISSUE THREAD

**Issue by jorgehatccrma** [fchollet/keras#4555]
I recently updated to keras v1.1.2 and I can't load a model from json that I'm able to load with v1.1.1.

A snippet to reproduce:

```
import keras
with open('/model/best_arch.json', 'r') as fh:
    arch = fh.read()
model = keras.models.model_from_json(arch)
```

When using v1.1.1 it returns a model, but with v1.1.2 I get

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-89dbc929bc53> in <module>()
----> 1 model = keras.models.model_from_json(arch)

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in model_from_json(json_string, custom_objects)
    207     from keras.utils.layer_utils import layer_from_config
    208     config = json.loads(json_string)
--> 209     return layer_from_config(config, custom_objects=custom_objects)
    210
    211

/usr/local/lib/python2.7/dist-packages/keras/utils/layer_utils.pyc in layer_from_config(config, custom_objects)
     32         layer_class = get_from_module(class_name, globals(), 'layer',
     33                                       instantiate=False)
---> 34     return layer_class.from_config(config['config'])
     35
     36

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in from_config(cls, config, custom_objects)
   2393
   2394         for layer_data in config['layers']:
-> 2395             process_layer(layer_data)
   2396
   2397         name = config.get('name')

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in process_layer(layer_data)
   2371             # Instantiate layer.
   2372             layer = layer_from_config(layer_data,
-> 2373                                       custom_objects=custom_objects)
   2374             created_layers[layer_name] = layer
   2375

/usr/local/lib/python2.7/dist-packages/keras/utils/layer_utils.pyc in layer_from_config(config, custom_objects)
     32         layer_class = get_from_module(class_name, globals(), 'layer',
     33                                       instantiate=False)
---> 34     return layer_class.from_config(config['config'])
     35
     36

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in from_config(cls, config)
   1465             output_shape = config['output_shape']
   1466
-> 1467         output_mask_type = config.pop('output_mask_type')
   1468         if output_mask_type == 'function':
   1469             output_mask = globals()[config['output_mask']]

KeyError: 'output_mask_type'
```

Let me know if you need the actual model architecture (the JSON). I prefer not to post it here, but I could send it somehow if necessary (although I suspect you won't need it). BTW, the model was created using keras 1.0.8, but it was loading fine with 1.1.1.

**Comment by dzhelonkin** [comment]
The same error with keras.model.load_model() function with 1.1.2 keras version using tensorflow 0.11.0rc2 backend.

**Comment by fchollet** [comment]
This is now fixed, please upgrade Keras.

**Comment by jorgehatccrma** [comment]
I confirm the fix works using the latest master. That said, 1.1.2 in PyPi is still broken. I'm not familiar with PyPi flow. It could be just a propagation time issue, or maybe you need to force push the latest version? Either way, thanks for the quick fix!
