### ISSUE TITLE
Possible bug with shared batch normalization + sequential model? [Script inside]

### ISSUE THREAD

**Issue by jmhessel** [fchollet/keras#4689]
When trying to share batch normalization layers, it looks like you can't use the sequential container as a function. For example, when `crash` is False in the following script, it runs fine. Otherwise, you get a theano/tensorflow error about variable naming.

```
import numpy as np
from keras.layers import Input, Dropout
from keras.layers.normalization import BatchNormalization
from keras.models import Sequential, Model

crash = True

x = np.random.normal(loc=5.0, scale=10.0, size=(2, 10))

x1 = Input(shape=(10,))
x2 = Input(shape=(10,))

# Test within sequential model
seq = Sequential()
if crash:
    seq.add(BatchNormalization(input_shape = (10,)))
if not crash:
    seq.add(Dropout(.5, input_shape = (10,)))
y3 = seq(x1)
y4 = seq(x2)

model = Model([x1,x2], [y3,y4])
model.compile('sgd','mse')
model.train_on_batch([x,x],[x,x])
```

For tensorflow the error is:
```
ValueError: Variable batchnormalization_1_running_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope?
```
For theano the error is:
```
ValueError: ('this shared variable already has an update expression', (batchnormalization_1_running_mean, Elemwise{add,no_inplace}.0))
```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
I have fixed this. TF was creating weights that it should not have created.

**Comment by jmhessel** [comment]
Thanks a bunch, this works on TF! :-) As a quick heads up -- this still doesn't work on the Theano backend still for me, as I still get the 

```
ValueError: ('this shared variable already has an update expression', (batchnormalization_1_running_mean, Elemwise{add,no_inplace}.0))
```

error

**Comment by fchollet** [comment]
@nouiz do you think it would be possible to create a number of update expressions for a variable, which would end up being averaged when compiling the graph?

In this case it would be useful for sharing a single batch norm layer without having its weights updates conditioned on only one of the different data streams it is exposed to.

**Comment by nouiz** [comment]
We already discussed what we should do when there is multiple updates for a
shared variable. There is many possible and sane way to handle this. The
average, but it could also be the sum. So we don't plan to do any of them
and let the user do this.

You can easily make some code in your wrapper of theano.function, that
would average the updates and pass that to theano.function().

On Mon, Dec 12, 2016 at 11:32 PM, François Chollet <notifications@github.com

**Comment by fchollet** [comment]
@nouiz additionally, is there any equivalent for `tf.assign_add`? We could implement a wrapper with equivalent behavior on the Keras side, but it would be a bit more involved. I imagine a `assign_add` update could be encoded as a tuple `('add', variable, increment)`, which would be converted to a regular update in the Keras `function` interface.

Basically I would like to be able to *sum* concurrent incremental updates to variables (specified via `assign_add`).

**Comment by nouiz** [comment]
I think inc_subtensor is what you want.

Suppose you do something like this normally:

    updates = [
        (param, param - learning_rate * gparam)
        for param, gparam in zip(classifier.params, gparams)
    ]


Here is speudo-code to what I have in mind:

clean_updates = {}
for k, v in zip(classifier.params, gparams)
   if k not in clean_updates:
      clean_updates[k] = v
   elif:
      clean_updates[k] += v
updates = [
        (param, param - learning_rate * gparam)
        for param, gparam in clean_updates.iteritems()
    ]

This will add all the gradients before scaling them by the learning rate.
You could scale them before adding them easily.

If that don't do what you want, tell me.

**Comment by jmhessel** [comment]
For folks reading this -- this script now works with both backends to my knowledge.

**Comment by DaveRichmond-** [comment]
Hi,

I'm having a similar problem.  Initially, I had the bug described by @jmhessel, on both my code and his example code.  I updated keras (I'm using tf backend), and now his example code runs, but my code gives a new error.

I have attached my code below.  I'm attempting to train a simple DC-GAN model on MNIST, and I run into problems when I include BatchNormalization in the discriminator, which is effectively shared across two models.  The code should run from command line and reproduce the error.

https://gist.github.com/DaveRichmond-/cd59c0e707dfc9666cca30bfec271388

In case it's helpful, the error is:

Invalid argument: You must feed a value for placeholder tensor 'input_5' with dtype float
	 [[Node: input_5 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Thanks very much for your help.  I'm finding keras to be extremely useful!

Best,
Dave

**Comment by botcs** [comment]
currently I dont have permission for upgrading the lib, also curious how should I surpass/solve this problem?

**Comment by meliscicek** [comment]
For me, with keras 2 and tensorflow 1.2, it does not work.

**Comment by JustinhoCHN** [comment]
@meliscicek keras 2.1.3 and tf 1.4 works! When I use tf 1.3, it didn't work.
