### ISSUE TITLE
Model.from_config(m.get_config()) doesn't work when a shared layer has inputs that depend on itself.

### ISSUE THREAD

**Issue by nur-ag** [fchollet/keras#6494]
The following script reproduces the issue. `ValueError: Missing layer: mix` is thrown when 
you try to copy the model, even though it compiles and can be trained just fine. I have looked at `keras/engine/topology.py`, trying to hack up a quick fix but that didn't get me far. It looks like it assumes all inputs for a layer will have been created before it, but I couldn't sort the layers to manage the actual dependencies. 

Also, if there is a better alternative to `frozen = Model.from_config(m.get_config())`, then `frozen.set_weights(m.get_weights())`, I'd love to know—this is the way I am 'freezing' the state of a model while I go on training with it.

```
import numpy as np
from keras.models import Model
from keras.layers import Input, Reshape, LSTM, Activation, add
from keras.layers.convolutional import Conv2D, MaxPooling2D


n = 256
sequence_length = 10
vector_length = 32


# create a model with two inputs
left = Input(name='left_in',  shape=(sequence_length, vector_length))
right = Input(name='right_in', shape=(sequence_length, vector_length))

# create a layer that we will use a few times
encoder = LSTM(vector_length, name='encoder', activation='tanh', implementation=2, return_sequences=True)

# apply the previous layer to one computation branch, mix with another
left_enc = encoder(left)
mix_enc = add([left_enc, right], name='mix')

# apply the re-usable layer to the mix
output = encoder(mix_enc)

# the model compiles and looks fine
m = Model(inputs=[left, right], outputs=output)
print m.summary()

m.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
left = right = output = np.random.random((n, sequence_length, vector_length))

# it can be fit...
m.fit({'left_in': left, 'right_in': right}, output, epochs=2, batch_size=32, verbose=0)

# but blows up if you try to copy it!
m_copy = Model.from_config(m.get_config())

```

EDIT: I don't think it matters in this case, but I'm using Theano.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by yreme** [comment]
I came across the same issue, and solved by `Sequential.from_config(`
```python
from keras.models import Sequential

config = model.get_config()
model_new = Sequential.from_config(config)
```

those two object are the same:
```python
>>> model
<keras.models.Sequential object at 0x1156ef750>
>>> model_new
<keras.models.Sequential object at 0x11575d790>
```

**Comment by nur-ag** [comment]
Sadly, that didn't solve it on Keras 2.0.4—plugging `m_copy = Sequential.from_config(m.get_config())
` instead produced a KeyError when accessing the config.

**Comment by yreme** [comment]
`Sequential.from_config ` not work in ` Keras 2.0.4`, and works in ` Keras 2.0.2` .

But `Model.from_config` works in ` Keras 2.0.4`, here is the code:
```python
>>> config = model.get_config()

>>> Model.from_config(config)
<keras.engine.training.Model object at 0x7f080aac2d90>
>>> model_new = Model.from_config(config)
>>> model_new
<keras.engine.training.Model object at 0x7f080aa32f50>
>>> model
<keras.engine.training.Model object at 0x7f080ab1d990>
>>> import keras
>>> keras.__version__
'2.0.4'

```

**Comment by nur-ag** [comment]
That's quite strange, when I use it alongside with the sample script I provided it doesn't work. That is:

```
import numpy as np
import keras
from keras.models import Model, Sequential
from keras.layers import Input, Reshape, LSTM, Activation, add
from keras.layers.convolutional import Conv2D, MaxPooling2D


n = 256
sequence_length = 10
vector_length = 32


# create a model with two inputs
left = Input(name='left_in',  shape=(sequence_length, vector_length))
right = Input(name='right_in', shape=(sequence_length, vector_length))

# create a layer that we will use a few times
encoder = LSTM(vector_length, name='encoder', activation='tanh', implementation=2, return_sequences=True)

# apply the previous layer to one computation branch, mix with another
left_enc = encoder(left)
mix_enc = add([left_enc, right], name='mix')

# apply the re-usable layer to the mix
output = encoder(mix_enc)

# the model compiles and looks fine
m = Model(inputs=[left, right], outputs=output)
print m.summary()

m.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
left = right = output = np.random.random((n, sequence_length, vector_length))

# it can be fit...
m.fit({'left_in': left, 'right_in': right}, output, epochs=2, batch_size=32, verbose=0)

# print out keras version to be sure
print(keras.__version__)

# but blows up if you try to copy it!
m_copy = Model.from_config(m.get_config())
```

Will print the Keras version and throw an exception on `Model.from_config(m.get_config())`. I'm getting the same results on both macOS 10.12.4 and Ubuntu 16, using with Python 2.7.

**Comment by yreme** [comment]
I  think the problem lies at 
```python
m = Model(inputs=[left, right], outputs=output)
```
you can try other type of model,  for example:
```python
from keras.layers import Input, Dense
from keras.models import Model

# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
```
then `Model.from_config` will work
```python
>>> Model.from_config(model.get_config())
<keras.engine.training.Model object at 0x7f07f045e910>
```
