### ISSUE TITLE
Keras HDF5Matrix not working for model.fit()

### ISSUE THREAD

**Issue by teaghan** [fchollet/keras#6874]
I am trying to use the keras.utils.io_utils.HDF5Matrix to deal with large datasets when training, but I am running in to a problem when trying to train. Running this example:
`
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.io_utils import HDF5Matrix
import numpy as np

def create_dataset():
    import h5py
    X = np.random.randn(200,10).astype('float32')
    y = np.random.randint(0, 2, size=(200,1))
    f = h5py.File('test.h5', 'w')
    # Creating dataset to store features
    X_dset = f.create_dataset('my_data', (200,10), dtype='f')
    X_dset[:] = X
    # Creating dataset to store labels
    y_dset = f.create_dataset('my_labels', (200,1), dtype='i')
    y_dset[:] = y
    f.close()

create_dataset()

# Instantiating HDF5Matrix for the training set, which is a slice of the first 150 elements
X_train = HDF5Matrix('test.h5', 'my_data', start=0, end=150)
y_train = HDF5Matrix('test.h5', 'my_labels', start=0, end=150)

# Likewise for the test set
X_test = HDF5Matrix('test.h5', 'my_data', start=150, end=200)
y_test = HDF5Matrix('test.h5', 'my_labels', start=150, end=200)

model = Sequential()
model.add(Dense(64, input_shape=(10,), activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='sgd')

# Note: you have to use shuffle='batch' or False with HDF5Matrix
model.fit(X_train, y_train, batch_size=32, shuffle='batch')

model.evaluate(X_test, y_test, batch_size=32)
`

returns the error:
`
AttributeErrorTraceback (most recent call last)
<ipython-input-3-02900751f245> in <module>()
     38 
     39 # Note: you have to use shuffle='batch' or False with HDF5Matrix
---> 40 model.fit(X_train, y_train, batch_size=32, shuffle='batch')
     41 
     42 model.evaluate(X_test, y_test, batch_size=32)

...

/opt/conda/lib/python2.7/site-packages/keras/utils/io_utils.pyc in __getitem__(self, key)
     63 
     64     def __getitem__(self, key):
---> 65         start, stop = key.start, key.stop
     66         if isinstance(key, slice):
     67             if start is None:

AttributeError: 'list' object has no attribute 'start'
`

I am wondering if this is just an error due to a recent update as it seems this example worked for others in the past. Even running the code:

`
print(y_train[10])
`

Returns a similar Error:

`
AttributeError: 'int' object has no attribute 'start'
`

Whereas

`
print(y_train[10:11])
`

Actually works and prints out:

`
[[1]]
`

**Comment by myronmurray** [comment]
I'm facing the same error with h5py/HDF5Matrix. In the interim, I was able to switch to a fit_generator and custom batch the data from the HDF5Matrix (which seems slower and more complex). My guess is the output range of y_train[a:b] from the generator works instead of iterating at the fit method with batch_size, but will need more time to test.

**Comment by fchollet** [comment]
Please look at the code and try to see if there is anything wrong with it.

You can also send a PR to add a unit test that would evidence the existence of a problem with HDF5Matrix. Then we can fix it.

**Comment by farizrahman4u** [comment]
Update keras. Issue fixed in #6502.

**Comment by teaghan** [comment]
keras is up-to-date. The problem still persists when running the above code

**Comment by tsnowak** [comment]
Confirmed issue, with keras 2.0.4. Updated to 2.0.5 and was fixed.

**Comment by teaghan** [comment]
It works! Thanks
