### ISSUE TITLE
Dimension error on metrics argument when updating to keras 2

### ISSUE THREAD

**Issue by samsinai** [fchollet/keras#8035]
I had a keras model that ran fine with keras 1, but having updated to keras 2 (and updated tensorflow) I now get an error trying to run this:

`vae.compile(optimizer="adam", loss=vae_loss,metrics=["categorical_accuracy","top_k_categorical_accuracy"])`

The following error shows up. 

`Dimension (-1) must be in the range [0, 2), where 2 is the number of dimensions in the input. for 'metrics_4/categorical_accuracy/ArgMax' (op: 'ArgMax') with input shapes: [?,?], [].`

The keras release notes doesn't mention anything about arguments of the categorical_accuracy metric to have changed. What am I missing?

**Comment by sunwell1994** [comment]
I have the same issues. how to deal with it

**Comment by samsinai** [comment]
It is fixed if your loss function is not using the "objectives" class from Keras 1, instead you should use the losses class.

**Comment by nsahin** [comment]
I still get the same error after changing to losses class:

model.compile(loss=losses.categorical_crossentropy, optimizer='sgd', metrics=['accuracy'])

Do you know how to fix this? Thanks

**Comment by Chandra-S-Narain-Kappera** [comment]
Did anyone solve this problem?

**Comment by bagolysz** [comment]
Same problem here. Any solution?

**Comment by jshobhit** [comment]
I ran into this problem only after I had updated my Tensorflow to the GPU optimized version that used CUDA. It worked properly before the upgrade. 

Maybe there is an issue with the %path% environment variable? I cannot think of anything else. Any solution would be greatly appreciated.

**Comment by weigi** [comment]
I have the exact same Problem as jshobhit. After updating to tensorflow-gpu i get this "ValueError: Dimension (-1) must be in the range [0, 2), where 2 is the number of dimensions in the input. for 'metrics/acc/ArgMax' (op: 'ArgMax') with input shapes: [?,?], []."

Help would be greatly appreciated :)

**Comment by MartinNowak** [comment]
Maybe try to update your tensorflow library to 1.x.y.

**Comment by change2014** [comment]
it worked for me by changing the syntax to 
model.compile(optimizer=keras.optimizers.Adadelta(),loss=keras.losses.categorical_crossentropy)

**Comment by mayank5695** [comment]
@change2014 If you remove metric then it will go away but you can't evaluate the matrix accuracy, only losses.
import keras.backend as K

def get_categorical_accuracy_keras(y_true, y_pred):
    return K.mean(K.equal(K.argmax(y_true, axis=1), K.argmax(y_pred, axis=1)))

model.compile(loss=losses.categorical_crossentropy, optimizer=sgd, metrics=[get_categorical_accuracy_keras])


I tried this and it works for me to calculate both losses and accuracy.
